services:
  pgdatabase:
    image: postgres:15-alpine
    restart: always
    environment: &postgres-vars
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE_DEV: ${POSTGRES_DATABASE_DEV}
      POSTGRES_DATABASE_PROD: ${POSTGRES_DATABASE_PROD}
    ports:
      - 5432:5432
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - default
  ingestion:
    environment: *postgres-vars
    build:
      context: ../..
      dockerfile: infra/local/Dockerfile
    depends_on:
      - pgdatabase
    stdin_open: true
    tty: true
    networks:
      - default
networks:
  default:
    driver: bridge
